version: "3"

services:
  viltasks:
    build:
     dockerfile: Dockerfile
     context: .
    image: mvilche/viltasks
    volumes:
      - data:/app/database
    ports:
      - "9000:9000"

volumes:
  data:
